<?php
/**
 * Copyright 2008 Chris Abernethy
 *
 * This file is part of Member Access.
 *
 * Member Access is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Member Access is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Member Access.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
?>
<fieldset class="inline-edit-group">
    <div class="inline-edit-col">
        <h4>Member Access</h4>
        <p><span class="title"><?php echo esc_html($this->get('current_state_message')) ?></span></p>
        <p><label><input style="vertical-align:middle;" name="<?php echo esc_attr($this->get('plugin_label') . '_visibility') ?>" type="radio" value="public" /> <span class="checkbox-title"><?php echo esc_html(__('Ignore the default settings and make this post visible to everyone', 'member_access')) ?></span></label></p>
        <p><label><input style="vertical-align:middle;" name="<?php echo esc_attr($this->get('plugin_label') . '_visibility') ?>" type="radio" value="private" /> <span class="checkbox-title"><?php echo esc_html(__('Ignore the default settings and make this post visible only to members', 'member_access')) ?></span></label></p>
        <p><label><input style="vertical-align:middle;" name="<?php echo esc_attr($this->get('plugin_label') . '_visibility') ?>" type="radio" value="default" /> <span class="checkbox-title"><?php echo esc_html(__('Honor the default post visibility settings', 'member_access')) ?></span></label></p>
    </div>
</fieldset>
